[project]
name = "work"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.133.1",
    "loguru>=0.7.3",
    "nanoid>=2.0.0",
    "passlib[bcrypt]>=1.7.4",
    "psycopg2>=2.9.11",
    "pydantic-settings>=2.13.1",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.22",
    "sqlmodel>=0.0.37",
    "uvicorn>=0.41.0",
    "loguru>=0.7.3",
    "nanoid>=2.0.0",
    "authlib>=1.6.8",
    "requests>=2.32.5",
    "itsdangerous>=2.2.0",
    "certifi>=2026.2.25",
    "pyjwt>=2.11.0",
    "httpx>=0.28.1",
]
#[[tool.uv.index]]
#url = "http://10.21.0.55:8081/repository/pypi/simple"
#default = true
